-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 11:56:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetdd_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetdd_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetdd_db` DEFAULT CHARACTER SET utf8 ;
USE `projetdd_db` ;

-- -----------------------------------------------------
-- Table `projetdd_db`.`hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetdd_db`.`hero` (
                                                    `heroId` INT NOT NULL,
                                                    `name` VARCHAR(45) NULL,
    `type` VARCHAR(45) NULL,
    `life` INT NULL,
    `strength` INT NULL,
    `position` INT NULL,
    PRIMARY KEY (`heroId`),
    UNIQUE INDEX `id_UNIQUE` (`heroId` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetdd_db`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetdd_db`.`board` (
                                                     `boardId` INT NOT NULL,
                                                     `board` JSON NULL,
                                                     PRIMARY KEY (`boardId`),
    UNIQUE INDEX `id_UNIQUE` (`boardId` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetdd_db`.`sauvegarde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetdd_db`.`sauvegarde` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `heroId` INT NOT NULL,
                                                          `boardId` INT NOT NULL,
                                                          PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_sauvegarde_hero_idx` (`heroId` ASC) VISIBLE,
    INDEX `fk_sauvegarde_board1_idx` (`boardId` ASC) VISIBLE,
    CONSTRAINT `fk_sauvegarde_hero`
    FOREIGN KEY (`heroId`)
    REFERENCES `projetdd_db`.`hero` (`heroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_sauvegarde_board1`
    FOREIGN KEY (`boardId`)
    REFERENCES `projetdd_db`.`board` (`boardId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
